### ISSUE TITLE
Database: Add Festivals

### ISSUE THREAD

**Issue by davidwobido** [davidwobido/festival-filter#18]
## Description
App needs at least 15 festivals. Will be added step-by-step when a coding break is needed.

## Tasks
- [ ] Add first 5 festivals
- [ ] Add second 5 festivals
- [ ] Add next 5 festivals
- [ ] Add additional festivals
