### ISSUE TITLE
Final tasks

### ISSUE THREAD

**Issue by davidwobido** [davidwobido/festival-filter#40]
## Description
Some tasks which should be done 

## Tasks
- [x] FestivalCardLarge: left column bold or medium
- [x] FestivalCardLarge: Close-Icon absolute (size changes atm)
- [ ] FestivalCardLarge: Add Back to top button
- [ ] All Festivals page: Search bar should always have same size as the width of the FestivalCardSmall rows
