### ISSUE TITLE
Storybook: Components

### ISSUE THREAD

**Issue by davidwobido** [davidwobido/festival-filter#7]
## Description
Add Components to storybook

## Tasks
- [x] Buttons
- [x] Links
- [x] Genre tags
- [x] Default bar
- [x] Small Festival Card
- [x] Medium Festival Card
- [x] Large Festival Card

## Screenshot
![image](https://user-images.githubusercontent.com/91462450/142906816-80c6064a-838a-4064-907f-631b1135d30c.png)
